### PR TITLE
Fix #79 add removePrefix,  removeSuffix, removeSurrounding

### LINKED ISSUE #79: Add String.removePrefix, removeSuffix, and removeSurrounding
I know these methods from Kotlin: they make development so much easier when you need those.

- `removePrefix`: removes a prefix from a string and returns that as a copy, otherwise returns a copy of the original string
- `removeSuffix`: same, but for suffix.
- `removeSurrounding`: removes a prefix and a suffix if and only if both exist - otherwise keeps that unchanged. Run [this Kotlin example](https://pl.kotl.in/gHyZlMRy_).

Would love to implement those as well!

### PR DESCRIPTION
**Pull request by mreichelt**

### CODE REVIEW

**Comment by mreichelt** [comment]
This was fun to implement, and should close #79.
One thing I was not sure yet how to handle this was: The parameters in `prefix` and `suffix` in `removeSurrounding` are named, but must be given - otherwise this will throw an exception. First I wanted to add the `meta` dependency in the pubspec to add `@required`, but then I thought that maybe with non-null support in Dart this will be handled anyway later.
What do you think @leisim @passsy? :-)

**Comment by leisim** [comment]
@mreichelt Thanks a lot for this PR. I would leave the parameters for now.

**Comment by mreichelt** [comment]
Thanks - then this PR is ready to be merged ✅

**Comment by passsy** [comment]
Thanks for you contribution!

**Pull request merged**
