### PR TITLE
fix compareTo function

### PR DESCRIPTION
**Pull request by CyJaySong**
fix compareTo function

### CODE REVIEW

**Comment by CyJaySong** [comment]
@passsy

**Comment by passsy** [comment]
please add tests showing the bug

**Comment by CyJaySong** [comment]
```
  List<int> intList = [3, 1, 2];
  List<double> doubleList = [3.1, 1.2, 2.3];
  List<BigInt> bigintList = [BigInt.from(3), BigInt.from(1), BigInt.from(2)];
  print('min in intList: ${intList.min()}');
  print('min in doubleList: ${doubleList.min()}');
  print('min in doubleList: ${bigintList.min()}');
  print('int data compareTo result: ${1.compareTo(3)}');
  print('int data compareTo result: ${1.2.compareTo(3.1)}');
  print('BigInt data compareTo result: ${BigInt.from(1).compareTo(BigInt.from(3))}');
 // min in intList: 1
 // min in doubleList: 1.2
 // min in doubleList: 2
 // int data compareTo result: -1
 // int data compareTo result: -1
 // BigInt data compareTo result: -2
```
Although the result range of the CompareTo function for int and double types is [-1,0,1], dart does not specify that it must be this way (as far as I know). If this rule is used by default, it may cause errors in the comparison results of other types of data

**Comment by CyJaySong** [comment]
@passsy

**Comment by passsy** [comment]
I added the tests, and can confirm that it fixes `minBy`

**Comment by CyJaySong** [comment]
Hope you can release the new version as soon as possible

**Pull request merged**
