### PR TITLE
Adding time extensions

### PR DESCRIPTION
**Pull request by shinayser**
Hello!

I got the code produced by jogboms on https://github.com/jogboms/time.dart and merged his great libraries into dartx.

This commit introduces all the jogbom's extensions to time types, like producing durations through integers and some other utility methods.

### CODE REVIEW

**Comment by leisim** [comment]
Thanks for your contribution!

The `.seconds`, `.milliseconds`, etc. getters are already defined on `num` so they will work on `int` and `double` ([Source](https://github.com/leisim/dartx/blob/master/dartx/lib/src/num.dart)).

The extensions on `Date` and `Duration` are new and I will merge them if you remove the int extensions.

**Comment by shinayser** [comment]
Just removed the duplicated int extensions!

**Comment by leisim** [comment]
> I have a slight tingle in my stomach that copying source code and tests may not be an elegant solution.

I agree. I would never copy your without asking. I actually took this functionality from Kotlin before your package was released.

> with your permission, the improvements on Time.dart to support both variants of num would indeed be a good idea and both libraries could exists as different entities. What do you think?

Yeah sure, no problem. Do you think I should remove all time related getters? My vision with `dartx` was to create a single library which contains every extension you could dream of because with Kotlin I always had to use multiple libraries with overlapping functionality and that was annoying and created name conflicts.

**Comment by shinayser** [comment]
My objective of doing the merge was to make dartx the only library needed for all this small extensions that we use all the time on our work days. 
In my opinion, one library with all extensions is much better than multiple multiple libraries. 

Imagine if you want to use timer extensions, you will have to import it manually. 
Than, if you want to use another extensions library, you will also have to import it manually. 
See the problem? Dartx fix it by doing just one import line.

**Comment by jogboms** [comment]
> I agree. I would never copy your without asking. I actually took this functionality from Kotlin before your package was released.

No issues really, I was just more worried on how to proceed when things start to diverge.

> Do you think I should remove all time related getters?

If you wouldn't mind, I could make Time.dart more robust with those inclusions.

> Kotlin I always had to use multiple libraries with overlapping functionality and that was annoying and created name conflicts.

At least with the current implementation of extensions for dart we shouldn't be worried about this, There is an open discussion about global scoping (even though I wouldn't want that to be honest) and that could break projects down the road for every one.

**Comment by rrousselGit** [comment]
+1 to @jogboms 

A more elegant solution is to have `dartx` depend on @jogboms's solution. Then use the `export` directive to expose them.

**Comment by leisim** [comment]
Shit sorry I edited you comment...

**Comment by leisim** [comment]
> A more elegant solution is to have `dartx` depend on @jogboms's solution. Then use the `export` directive to expose them.

I didn't even think of that. Great idea. I'll do that if @jogboms agrees 👍

**Comment by jogboms** [comment]
@rrousselGit good of you to join in :)

> In my opinion, one library with all extensions is much better than multiple multiple libraries.

@shinayser, considering the fact that extensions are scoped to their imports, I would not think this is the way to go.

**Comment by jogboms** [comment]
@leisim I was already edging towards that idea in my mind. Good to know we are all in sync 💙 👍

**Comment by shinayser** [comment]
Awesome. So, making dartx depend on dart will be the best sollution.

Will you do this @leisim, or you want me to push that change?

**Comment by leisim** [comment]
> @leisim I was already edging towards that idea in my mind. Good to know we are all in sync 💙 👍

Perfect, let's do that. You create extensions for `num`, right?

**Comment by leisim** [comment]
> Awesome. So, making dartx depend on dart will be the best sollution.

This is also a future proof solution to solve these kinds of conflict.

**Comment by jogboms** [comment]
Yes @leisim will do that and add more tests.

**Comment by shinayser** [comment]
Great then. So, this issue is closed. Thanks @leisim and @jogboms.

Let's keep dart rocking :)

**Comment by rrousselGit** [comment]
That was a nice smooth discussion! Epic ❤️

**Comment by leisim** [comment]
@jogboms @rrousselGit @shinayser 

I made the changes and added a [small example](https://github.com/leisim/dartx#time-utils) to the readme. A new version will be published once `time.dart` supports num.

**Comment by shinayser** [comment]
> I made the changes and added a [small example](https://github.com/leisim/dartx#time-utils) to the readme. A new version will be published once `time.dart` supports num.

Amazing! Can't wait to use it with Flutter! Anyone got any idea when we getting dart 2.6 on it?

**Comment by jogboms** [comment]
@shinayser not so sure on the timeline.

@leisim published v1.1.0 of Time.dart

**Pull request closed without merging**
