### PR TITLE
Added all HttpRequest Extensions from https://github.com/TechSar-dev/…

### PR DESCRIPTION
**Pull request by g5becks**
I was recently about to start work on a similar project which aims to simplify the Dart SDK API. It's a huge task and will take time, so I am adding things as I need them. I would like to merge what I have so far and work on this project moving forward. 

Hopefully this pr is acceptable, if not - please let me know if I need to change anything to meet the conventions of this library. 

Thanks.

### CODE REVIEW

**Comment by leisim** [comment]
Wow thanks, that's amazing! Do you also have unit tests?

**Comment by G5Becks** [comment]
Hi, I haven't had a chance to add any tests as of yet. They are all just getters and setters, but I can add a bunch of tests over the weekend and do another pr once that's complete.

**Comment by leisim** [comment]
Maybe we create a dev branch and you open another PR so we can work together on tests...

**Comment by leisim** [comment]
Could you please open another PR against the "develop" branch.

**Comment by g5becks** [comment]
Just opened it.

**Pull request closed without merging**
