### PR TITLE
Add median to iterable_num

### PR DESCRIPTION
**Pull request by AKushWarrior**
I added a median function to iterable_num.

I also reformatted the zero argument functions to getters (which improves readability IMO). I also updated the documentation of average to reflect the actual function.

EDIT: probably shouldn't have changed to getters; it's pretty useless and might break code unnecessarily. Will update PR...

### CODE REVIEW

**Comment by AKushWarrior** [comment]
Whoops, didn't realize that the tests were based around the current, non-getter API. Will fix and re-pull...

**Comment by AKushWarrior** [comment]
Median seems like a logical accompaniment to mean, and has a use-case.

In a similar vein, mode might also be included. However, the mode use-case is too niche for this package, I think.

Also, I noticed that the average documentation was a bit inaccurate, so I cleaned it up...

**Comment by passsy** [comment]
I'm fine with adding `median` but please add tests

**Comment by AKushWarrior** [comment]
@passsy median tests and null handling have been added

**Comment by passsy** [comment]
Thanks for your contribution. is `mode()` next? 😉

**Comment by AKushWarrior** [comment]
Haha, we'll see.

In all seriousness, I might make a PR with some more basic stats (mode, std dev, variance?).

**Pull request merged**
