### PR TITLE
Add Object.as<T>()

### PR DESCRIPTION
**Pull request by yongjhih**
Similar to `as? T` in Kotlin.

```dart
Text((ModalRoute.of(context).settings.argument?.as<User>() ?? User.empty()).name);
```

```dart
   test('.as<T>()', () async {
      const Object it = "Hello";
      expect(it.as<String>() ?? "", "Hello");
      expect(it.as<int>(), null);
      expect(it.as<int>() ?? 0, 0);
    });
```

### CODE REVIEW

**Comment by passsy** [comment]
Are there cases where `.as<R>()` is easier to use than `as R`?

I would even argue that it is easier to read without the extension
```dart
Text((ModalRoute.of(context).settings.arguments as User ?? User.empty()).name);
```

Also `cast<R>()` might be a better name because it is the same as [`Iterable.cast`](https://api.dart.dev/stable/2.7.0/dart-core/Iterable/cast.html)

**Comment by leisim** [comment]
I think there will be an `as?` operator once NNBD is released. So I would wait for that.

**Comment by yongjhih** [comment]
>  I would even argue that it is easier to read without the extension
> ```dart
> Text((ModalRoute.of(context).settings.arguments as User ?? User.empty()).name);
> ```

You might get a casting exception there.

```dart
type 'xxx' is not a subtype of type 'User' in type cast
```

That's why Kotlin needs `as?`.

If you want to null-safety cast in dart for now:

```dart
Text(
  (ModalRoute.of(context).settings.arguments != null &&
    ModalRoute.of(context).settings.arguments is User)
  ? ModalRoute.of(context).settings.arguments.name // hopefully there is a smart casting
  : User.empty().name
```

> Also cast<R>() might be a better name because it is the same as Iterable.cast
Let's look this:

```dart
<int>[1, 2, 3].cast<num>();
```

vs.

```dart
<int>[1, 2, 3] as num;
```

That's why I think we shouldn't use `cast` name for Object casting.

@leisim 

Agreed with you, we may should wait for NNBD released.

**Comment by passsy** [comment]
I didn't know/remember that `as?` in Kotlin is a ["Safe" (nullable) cast operator](https://kotlinlang.org/docs/reference/typecasts.html#safe-nullable-cast-operator). I wrongly assumed the question mark was required for nullable types.

I agree that we should wait what NNBD brings, which I expect to land soonish.

**Pull request closed without merging**
